name: Run Autotrader Bot

on:
  # every 15 minutes (UTC)
  schedule:
    - cron: '*/15 * * * *'
  # manual “Run workflow” button
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    # allow the workflow’s GITHUB_TOKEN to push changes
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          SEARCH_URL:         ${{ secrets.SEARCH_URL }}
          GMAIL_USER:         ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}   # ← fixed
          TWILIO_SID:         ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN:       ${{ secrets.TWILIO_TOKEN }}
          TWILIO_FROM:        ${{ secrets.TWILIO_FROM }}
          TWILIO_TO:          ${{ secrets.TWILIO_TO }}
        run: python autotrader_bot.py

      - name: Commit & push updates
        if: success() && (hashFiles('seen_listings.json') != '' || hashFiles('archives/**') != '')
        run: |
          git config user.name  "autotrader-bot"
          git config user.email "actions@github.com"
          git add seen_listings.json archives || true
          git commit -m "Update seen listings and archives [skip ci]" || exit 0
          git push origin HEAD:main
